/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-14 09:36:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notices_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/recruit-app/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/recruit-app/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716272562048L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/content/css/ver_2/mtc/mtc_lounge-sv-202402231655.css\" rel=\"stylesheet\" type=\"text/css\" /><!--  -->\r\n");
      out.write("<link href=\"https://i.jobkorea.kr/content/css/ver_2/help/help-sv-202402231655.css\" rel=\"stylesheet\" type=\"text/css\" /><!--  -->\r\n");
      out.write("<!-- 파비콘 -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"https://static.wanted.co.kr/favicon/new/favicon.ico\"/>\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("<link href=\"../assets/css/company/company-info-list-6.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- bootstrap -->\r\n");
      out.write("\r\n");
      out.write("<!--jQuery CDN 시작-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("<!--jQuery CDN 끝-->\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/lib.jsp", out, false);
      out.write("  \r\n");
      out.write("	<!-- golgolz start -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		<!-- golgolz start -->\r\n");
      out.write("		<!-- golgolz end -->\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("		<!-- golgolz start -->\r\n");
      out.write("		$(\"#category\").change(function() {\r\n");
      out.write("	        var category = $(\"#category\").val();\r\n");
      out.write("	        \r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            url : \"/recruit-app/notice/noticesByCategory.do\",\r\n");
      out.write("	            type : \"GET\", \r\n");
      out.write("	            dataType : \"JSON\", \r\n");
      out.write("	            data: {\r\n");
      out.write("	                \"category\" : category\r\n");
      out.write("	            },\r\n");
      out.write("	            error : function(xhr) {\r\n");
      out.write("	                console.error(xhr);\r\n");
      out.write("	                alert(\"일시적인 오류입니다. 잠시 후 다시 시도해주세요.\");\r\n");
      out.write("	            },\r\n");
      out.write("	            success : function(data) {\r\n");
      out.write("	                var noticeList = data.noticeList;\r\n");
      out.write("	                var tableBody =\"\";\r\n");
      out.write("	                noticeList.forEach(function(notice) {\r\n");
      out.write("	                    var date = new Date(notice.input_date);\r\n");
      out.write("	                    var dateString = date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + ('0' + date.getDate()).slice(-2);								\r\n");
      out.write("	                    \r\n");
      out.write("	                    tableBody += \"<tr class='primary'>\"+\r\n");
      out.write("	                                    \"<td class='sort'>\" + notice.category + \"</td>\" +\r\n");
      out.write("	                                    \"<td class='alLeft'><span class='tit'><a href='http://localhost/recruit-app/notice/detail.do?notice_num=\" + notice.notice_num + \"'>\" + notice.title + \"</a></span></td>\" +\r\n");
      out.write("	                                    \"<td class='date'>\" + dateString + \"</td>\" +\r\n");
      out.write("	                                \"</tr>\";\r\n");
      out.write("	                });\r\n");
      out.write("	                $(\"table tbody\").html(tableBody);\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    });\r\n");
      out.write("/////////////////////////\r\n");
      out.write("	    // 검색 버튼 클릭 시\r\n");
      out.write("	    $(\"#searchBtn\").click(function() {\r\n");
      out.write("	        searchNotices();\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    // 검색어 입력란에서 Enter 키 입력 시\r\n");
      out.write("	    $(\"#lb_sch\").keydown(function(event) {\r\n");
      out.write("	        if (event.keyCode === 13) {\r\n");
      out.write("	            searchNotices();\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    function searchNotices() {\r\n");
      out.write("	        var keyword = $(\"#lb_sch\").val();\r\n");
      out.write("	        var searchType = $(\"#lb_view_1\").val(); // 선택한 검색 옵션 가져오기\r\n");
      out.write("\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            url: \"/recruit-app/notice/noticesbyKeyword.do\",\r\n");
      out.write("	            type: \"GET\",\r\n");
      out.write("	            dataType: \"JSON\",\r\n");
      out.write("	            data: {\r\n");
      out.write("	                \"keyword\": keyword,\r\n");
      out.write("	                \"searchType\": searchType\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function(xhr, status, errorThrown) {\r\n");
      out.write("	                console.error(\"AJAX Error: \", status, errorThrown);\r\n");
      out.write("	                console.error(\"Response: \", xhr.responseText);\r\n");
      out.write("	                alert(\"일시적인 오류입니다. 잠시 후 다시 시도해주세요.\");\r\n");
      out.write("	            },\r\n");
      out.write("	            success: function(data) {\r\n");
      out.write("	                var noticeList = Array.isArray(data.noticeList) ? data.noticeList : (Array.isArray(data) ? data : []);\r\n");
      out.write("	                var tableBody = \"\";\r\n");
      out.write("\r\n");
      out.write("	                noticeList.forEach(function(notice) {\r\n");
      out.write("	                    if (!notice || !notice.input_date || !notice.notice_num || !notice.title || !notice.category) {\r\n");
      out.write("	                        return;\r\n");
      out.write("	                    }\r\n");
      out.write("\r\n");
      out.write("	                    var date = new Date(notice.input_date);\r\n");
      out.write("	                    var dateString = date.getFullYear() + '-' + ('0' + (date.getMonth() + 1)).slice(-2) + '-' + ('0' + date.getDate()).slice(-2);\r\n");
      out.write("\r\n");
      out.write("	                    tableBody += \"<tr class='primary'>\" +\r\n");
      out.write("	                        \"<td class='sort'>\" + notice.category + \"</td>\" +\r\n");
      out.write("	                        \"<td class='alLeft'><span class='tit'><a href='http://localhost/recruit-app/notice/detail.do?notice_num=\" + notice.notice_num + \"'>\" + notice.title + \"</a></span></td>\" +\r\n");
      out.write("	                        \"<td class='date'>\" + dateString + \"</td>\" +\r\n");
      out.write("	                        \"</tr>\";\r\n");
      out.write("	                });\r\n");
      out.write("\r\n");
      out.write("	                $(\"table tbody\").html(tableBody);\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("		<!-- golgolz end -->\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"__next\" data-reactroot=\"\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<main class=\"JobsFeed_Jobsfeed__DpeV9\">\r\n");
      out.write("			<section class=\"Section_Section__P1hhc\">\r\n");
      out.write("				<!-- golgolz start -->\r\n");
      out.write("				<div>\r\n");
      out.write("					<div class=\"loungeContent noticeListContent\"\r\n");
      out.write("						style=\"width: 100%; max-width: 1300px; margin: 30px auto; box-sizing: border-box; padding: 20px;\">\r\n");
      out.write("						<!-- <div class=\"loungeContent noticeListContent\" style=\"margin:40px auto 0; width:1300px\"> -->\r\n");
      out.write("						<div class=\"topHdWrap clear\">\r\n");
      out.write("							<h2 class=\"lug_hd_2\">공지사항</h2>\r\n");
      out.write("							<form action=\"#\">\r\n");
      out.write("\r\n");
      out.write("								<fieldset>\r\n");
      out.write("									<legend>공지사항 검색</legend>\r\n");
      out.write("									<div class=\"searchBarItem mtcPlaceholder\" style=\"float: right\">\r\n");
      out.write("										<span class=\"phTx\"></span> <input type=\"text\" id=\"lb_sch\"\r\n");
      out.write("											class=\"mtcSchInp\" title=\"검색어 입력\">\r\n");
      out.write("										<!-- <input type=\"button\" class=\"mtcBtnB mtcSchBtn\" value=\"검색\"/> -->\r\n");
      out.write("										<button type=\"button\" id=\"searchBtn\" class=\"mtcBtnB mtcSchBtn\">\r\n");
      out.write("											<span class=\"skip\">검색</span>\r\n");
      out.write("										</button>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<select id=\"lb_view_1\"\r\n");
      out.write("										style=\"width: 100px; height: 36px; border: 0.2px solid #ced4da; margin-right: 10px\">\r\n");
      out.write("										<!-- <select name=\"\" id=\"lb_view_1\" title=\"문의 종류 선택\"> -->\r\n");
      out.write("										<option value=\"선택\" selected>선택</option>\r\n");
      out.write("										<option value=\"제목\">제목</option>\r\n");
      out.write("										<option value=\"내용\">내용</option>\r\n");
      out.write("										<option value=\"제목+내용\">제목+내용</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</fieldset>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"schListWrap\">\r\n");
      out.write("							<div class=\"mtcSchListTb\">\r\n");
      out.write("								<table summary=\"\">\r\n");
      out.write("									<caption>공지사항</caption>\r\n");
      out.write("									<colgroup>\r\n");
      out.write("										<col class=\"col_1\">\r\n");
      out.write("										<col class=\"col_2\">\r\n");
      out.write("										<col class=\"col_3\">\r\n");
      out.write("									</colgroup>\r\n");
      out.write("									<thead>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th scope=\"col\">\r\n");
      out.write("												<div style=\"float: left; padding-left: 15px\">\r\n");
      out.write("													<select id=\"category\" name=\"category\"\r\n");
      out.write("														style=\"width: 80px; height: 36px; border: 0.2px solid #FFFFFF;\">\r\n");
      out.write("														<option value=\"전체\" selected>전체</option>\r\n");
      out.write("														<option value=\"안내\">안내</option>\r\n");
      out.write("														<option value=\"서비스종료\">서비스종료</option>\r\n");
      out.write("														<option value=\"이벤트\">이벤트</option>\r\n");
      out.write("													</select>\r\n");
      out.write("												</div>\r\n");
      out.write("											</th>\r\n");
      out.write("											<th scope=\"col\">제목</th>\r\n");
      out.write("											<th scope=\"col\">날짜</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</thead>\r\n");
      out.write("									<tbody>\r\n");
      out.write("										");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									</tbody>\r\n");
      out.write("								</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								<div class=\"listBtmArea\" style=\"margin-bottom: 40px\">\r\n");
      out.write("									<div class=\"btnListExDn\"></div>\r\n");
      out.write("\r\n");
      out.write("									<div style=\"text-align: center; margin-top: 30px\">\r\n");
      out.write("										<nav aria-label=\"...\">\r\n");
      out.write("											<ul class=\"pagination pagination-lg\"\r\n");
      out.write("												style=\"display: inline-flex;\">\r\n");
      out.write("												<li class=\"page-item disabled\"><span class=\"page-link\">&lt;</span>\r\n");
      out.write("												</li>\r\n");
      out.write("\r\n");
      out.write("												<li class=\"page-item active\" aria-current=\"page\"><span\r\n");
      out.write("													class=\"page-link\">1</span></li>\r\n");
      out.write("												<!-- <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("												<li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li> -->\r\n");
      out.write("\r\n");
      out.write("												<li class=\"page-item\"><a class=\"page-link\" href=\"#\">&gt;</a>\r\n");
      out.write("												</li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</nav>\r\n");
      out.write("									</div>\r\n");
      out.write("									");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("			</section>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("			</section>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/footer.jsp", out, false);
      out.write("  \r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/notice/notices.jsp(187,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("notice");
      // /WEB-INF/views/notice/notices.jsp(187,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/notice/notices.jsp(187,10) '${noticeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${noticeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("											<tr class=primary>\r\n");
            out.write("												<td class=\"sort\">");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("												<td class=\"alLeft\"><span class=\"tit\"><a\r\n");
            out.write("														href=\"http://localhost/recruit-app/notice/detail.do?notice_num=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.notice_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</a></span></td>\r\n");
            out.write("												<td class=\"date\">");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\r\n");
            out.write("											</tr>\r\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/notice/notices.jsp(189,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.category}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/notice/notices.jsp(191,99) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/notice/notices.jsp(193,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.input_date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/notice/notices.jsp(193,29) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
