/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-11 09:02:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.recruit;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/lib.jsp", out, false);
      out.write("  \r\n");
      out.write("	<!-- golgolz start -->\r\n");
      out.write("    <link href=\"http://localhost/recruit-app/assets/css/recruit/view-sv-202405201324.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\" integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("	<style text=\"text/css\">\r\n");
      out.write("		<!-- golgolz start -->\r\n");
      out.write("		#container, .container{\r\n");
      out.write("		    width: 1200px;\r\n");
      out.write("		}\r\n");
      out.write("		p{\r\n");
      out.write("			font-size: 14px;\r\n");
      out.write("		}\r\n");
      out.write("		.artReadJobSum .tbList > dd, .artReadJobSum .tbList > dt {\r\n");
      out.write("			font-size: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		<!-- golgolz end -->\r\n");
      out.write("	</style>\r\n");
      out.write("	<script text=\"text/javascript\">\r\n");
      out.write("		var company = \"\";\r\n");
      out.write("		\r\n");
      out.write("		$(function(){\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("			$.ajax({\r\n");
      out.write("	            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/recruit.do?id=\" + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recruitNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("	            method: 'GET',\r\n");
      out.write("	            dataType: 'JSON',\r\n");
      out.write("	            success: function(data) {\r\n");
      out.write("	            	console.log(data);\r\n");
      out.write("	            	renderRecruitData(data);\r\n");
      out.write("	            	company = data.companyCode;\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function(xhr, status, error) {\r\n");
      out.write("	                console.error(\"Error fetching data: \" + error);\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("			\r\n");
      out.write("			$(\"#devApplyBtn1\").click(function(){\r\n");
      out.write("		        var url = 'http://localhost/recruit-app/resume/resumes.do?recruit=' + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recruitNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("		        \r\n");
      out.write("		        window.location.href = url;\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(\"#devApplyBtn2\").click(function(){\r\n");
      out.write("		        var url = 'http://localhost/recruit-app/resume/resumes.do?recruit=' + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recruitNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("		        \r\n");
      out.write("		        window.location.href = url;\r\n");
      out.write("			});\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		function renderRecruitData(Recruit) {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/api/welfares.do?company=\" + Recruit.companyCode,\r\n");
      out.write("				method: 'GET',\r\n");
      out.write("	            dataType: 'JSON',\r\n");
      out.write("	            success: function(data) {\r\n");
      out.write("	            	updateWelfare(data);\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function(xhr, status, error) {\r\n");
      out.write("	                console.error(\"Error fetching data: \" + error);\r\n");
      out.write("	            }\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$('.coName').text(Recruit.companyName);\r\n");
      out.write("		    var h3Element = $('.hd_3');\r\n");
      out.write("		    var headerDiv = h3Element.find('.header');\r\n");
      out.write("		    h3Element.contents().filter(function() {\r\n");
      out.write("		        return this.nodeType === 3; // 텍스트 노드\r\n");
      out.write("		    }).remove();\r\n");
      out.write("		    h3Element.append(document.createTextNode(Recruit.title));\r\n");
      out.write("		    h3Element.prepend(headerDiv);\r\n");
      out.write("\r\n");
      out.write("		    $('.tbList dt:contains(\"경력\") + dd strong').text(Recruit.careerStandard);\r\n");
      out.write("		    switch (Recruit.eduStandard) {\r\n");
      out.write("		        case \"1\":\r\n");
      out.write("		            $('.tbList dt:contains(\"학력\") + dd strong').text('고등학교 졸업 이상');\r\n");
      out.write("		            break;\r\n");
      out.write("		        case \"2\":\r\n");
      out.write("		            $('.tbList dt:contains(\"학력\") + dd strong').text('대학교(2,3년제) 졸업 이상');\r\n");
      out.write("		            break;\r\n");
      out.write("		        case \"3\":\r\n");
      out.write("		            $('.tbList dt:contains(\"학력\") + dd strong').text('대학교(4년제) 졸업 이상');\r\n");
      out.write("		            break;\r\n");
      out.write("		        case \"4\":\r\n");
      out.write("		            $('.tbList dt:contains(\"학력\") + dd strong').text('대학원(석사) 졸업 이상');\r\n");
      out.write("		            break;\r\n");
      out.write("		        case \"5\":\r\n");
      out.write("		            $('.tbList dt:contains(\"학력\") + dd strong').text('대학원(박사) 졸업 이상');\r\n");
      out.write("		            break;\r\n");
      out.write("		        default:\r\n");
      out.write("		            $('.tbList dt:contains(\"학력\") + dd strong').text('학력무관');\r\n");
      out.write("		    }\r\n");
      out.write("		    \r\n");
      out.write("		    $('.tbList dt:contains(\"고용형태\") + dd strong').text(Recruit.hireCategory);\r\n");
      out.write("		    $('.tbList dt:contains(\"급여\") + dd').text(Recruit.salary + \" 만원\");\r\n");
      out.write("		    $('.tbList dt:contains(\"지역\") + dd').text(Recruit.workPlace);\r\n");
      out.write("		    $('.tbList dt:contains(\"시간\") + dd span.tahoma:first').text(Recruit.workDay);\r\n");
      out.write("		    $('.tbList dt:contains(\"시간\") + dd span.tahoma:last').text(Recruit.workTime);\r\n");
      out.write("		    $('#recruitContent').html(Recruit.content);\r\n");
      out.write("		    \r\n");
      out.write("		    const today = new Date();\r\n");
      out.write("		    const endDate = new Date(Recruit.endDate);\r\n");
      out.write("		    updateDateInfo(Recruit.inputDate, Recruit.endDate);\r\n");
      out.write("		    \r\n");
      out.write("		    if (today > endDate) {\r\n");
      out.write("		        replaceApplyButton('.tbOline .btn');\r\n");
      out.write("		        replaceApplyButton('.sumBtn');\r\n");
      out.write("		    } else {\r\n");
      out.write("		        $('.devOnlineApplyBtn').on('click', function() {\r\n");
      out.write("		            console.log('지원하기 버튼이 클릭되었습니다.');\r\n");
      out.write("		        });\r\n");
      out.write("		        updateCountdown(endDate);\r\n");
      out.write("		        countdownTimer = setInterval(() => updateCountdown(endDate), 1000);\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function updateCountdown(endDate) {\r\n");
      out.write("		    const today = new Date();\r\n");
      out.write("		    const distance = endDate - today;\r\n");
      out.write("\r\n");
      out.write("		    const days = Math.floor(distance / (1000 * 60 * 60 * 24));\r\n");
      out.write("		    const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));\r\n");
      out.write("		    const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));\r\n");
      out.write("		    const seconds = Math.floor((distance % (1000 * 60)) / 1000);\r\n");
      out.write("\r\n");
      out.write("		    let countdownText = '';\r\n");
      out.write("		    if (days > 0) {\r\n");
      out.write("		        countdownText += days + \"일 \";\r\n");
      out.write("		    }\r\n");
      out.write("		    countdownText += hours.toString().padStart(2, '0') + ':' + \r\n");
      out.write("				            minutes.toString().padStart(2, '0') + ':' + \r\n");
      out.write("				            seconds.toString().padStart(2, '0');\r\n");
      out.write("		    $('.devRemainCount .tahoma').text(countdownText);\r\n");
      out.write("\r\n");
      out.write("		    if (distance < 0) {\r\n");
      out.write("		        clearInterval(countdownTimer);\r\n");
      out.write("		        $('.devRemainCount .tahoma').text('마감됨');\r\n");
      out.write("		        replaceApplyButton('.tbOline .btn');\r\n");
      out.write("		        replaceApplyButton('.sumBtn');\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function updateDateInfo(inputDate, endDate) {\r\n");
      out.write("		    var startDate = new Date(inputDate);\r\n");
      out.write("		    var startDateStr = startDate.getFullYear() + '.' + \r\n");
      out.write("		                       (startDate.getMonth() + 1).toString().padStart(2, '0') + '.' + \r\n");
      out.write("		                       startDate.getDate().toString().padStart(2, '0');\r\n");
      out.write("		    var startDayOfWeek = ['일', '월', '화', '수', '목', '금', '토'][startDate.getDay()];\r\n");
      out.write("		    $('.date dt:contains(\"시작일\") + dd .tahoma').text(startDateStr);\r\n");
      out.write("		    $('.date dt:contains(\"시작일\") + dd').append('(' + startDayOfWeek + ')');\r\n");
      out.write("\r\n");
      out.write("		    var endDateObj = new Date(endDate);\r\n");
      out.write("		    var endDateStr = endDateObj.getFullYear() + '.' + \r\n");
      out.write("		                     (endDateObj.getMonth() + 1).toString().padStart(2, '0') + '.' + \r\n");
      out.write("		                     endDateObj.getDate().toString().padStart(2, '0');\r\n");
      out.write("		    var endDayOfWeek = ['일', '월', '화', '수', '목', '금', '토'][endDateObj.getDay()];\r\n");
      out.write("		    $('.date dt:contains(\"마감일\") + dd .tahoma').text(endDateStr);\r\n");
      out.write("		    $('.date dt:contains(\"마감일\") + dd').append('(' + endDayOfWeek + ')');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		let countdownTimer;\r\n");
      out.write("		$(window).on('unload', function() {\r\n");
      out.write("		    if (countdownTimer) {\r\n");
      out.write("		        clearInterval(countdownTimer);\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		function updateWelfare(welfareData) {\r\n");
      out.write("		    var $welfareContainer = $('.location .tbRow dl:first dd');\r\n");
      out.write("		    console.log(\"welfareData : \", welfareData);\r\n");
      out.write("		    $welfareContainer.find('dl').remove();\r\n");
      out.write("\r\n");
      out.write("		    if (welfareData.length > 0) {\r\n");
      out.write("		        var firstItem = welfareData[0];\r\n");
      out.write("		        $welfareContainer.find('dl:first dt').text(firstItem.category);\r\n");
      out.write("		        $welfareContainer.find('dl:first dd').text(firstItem.content);\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("		    for (var i = 1; i < welfareData.length; i++) {\r\n");
      out.write("		        var item = welfareData[i];\r\n");
      out.write("		        var $newDl = $('<dl>');\r\n");
      out.write("		        $newDl.append('<dt>' + item.category + '</dt>');\r\n");
      out.write("		        $newDl.append('<dd>' + item.content + '</dd>');\r\n");
      out.write("		        $welfareContainer.append($newDl);\r\n");
      out.write("		    }\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"__next\" data-reactroot=\"\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<main class=\"JobsFeed_Jobsfeed__DpeV9\">  \r\n");
      out.write("			<section class=\"Section_Section__P1hhc\">\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("				<div id=\"wrap\" style=\"margin-bottom: 30px; margin-top: 37px;\">\r\n");
      out.write("					<section id=\"container\" style=\"width:1100px;\">\r\n");
      out.write("						<h2 class=\"tpl_hd_1\" style=\"font-size: 36px; margin-top: 42px; font-weight: bold;\">\r\n");
      out.write("							채용 공고 상세 보기\r\n");
      out.write("						</h2>\r\n");
      out.write("						<section class=\"secReadSummary\">\r\n");
      out.write("							<h2 class=\"hd_2 blind\">요약정보</h2>\r\n");
      out.write("							<div class=\"readSumWrap clear\" style=\"width:1100px;\">\r\n");
      out.write("								<article class=\"artReadJobSum\" style=\"width:1100px;\">\r\n");
      out.write("									<div class=\"sumTit\">\r\n");
      out.write("										<h3 class=\"hd_3\" style=\"width: 1060px;\">\r\n");
      out.write("											<div class=\"header\">\r\n");
      out.write("												<span class=\"coName\"></span>\r\n");
      out.write("											</div>\r\n");
      out.write("										</h3>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"tbRow clear\">\r\n");
      out.write("										<div class=\"tbCol\" style=\"font-size: 14px;\">\r\n");
      out.write("											<h2 class=\"hd_2\">지원자격</h2>\r\n");
      out.write("											<dl class=\"tbList\">\r\n");
      out.write("												<dt>경력</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<strong class=\"col_1\">신입·경력</strong>\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>학력</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<strong class=\"col_1\">학력무관</strong>\r\n");
      out.write("												</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"tbCol\">\r\n");
      out.write("											<h2 class=\"hd_2\">근무조건</h2>\r\n");
      out.write("											<dl class=\"tbList\">\r\n");
      out.write("												<dt>고용형태</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<ul class=\"addList\">\r\n");
      out.write("														<li>\r\n");
      out.write("															<strong class=\"col_1\"></strong> \r\n");
      out.write("														</li>\r\n");
      out.write("													</ul>\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>급여</dt>\r\n");
      out.write("												<dd></dd>\r\n");
      out.write("												<dt>지역</dt>\r\n");
      out.write("												<dd></dd>\r\n");
      out.write("												<dt>시간</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<span class=\"tahoma\"></span>\r\n");
      out.write("													<span class=\"tahoma\"></span>\r\n");
      out.write("												</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"tbCol tbCoInfo\">\r\n");
      out.write("											<h2 class=\"hd_2\">기업정보</h2>\r\n");
      out.write("											<dl class=\"tbList\">\r\n");
      out.write("												<dt>사원수</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<span class=\"tahoma\">185</span>명\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>설립년도</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<text> <span class=\"tahoma\">1999</span>년 (<span\r\n");
      out.write("														class=\"tahoma\">26</span>년차) </text>\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>기업형태</dt>\r\n");
      out.write("												<dd>중견기업 (비상장)</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("											<div class=\"coBtn\">\r\n");
      out.write("												<a\r\n");
      out.write("													href=\"https://www.jobkorea.co.kr/Recruit/Co_Read/C/487603?Oem_Code=C1\"\r\n");
      out.write("													target=\"_blank\" title=\"새창\" class=\"girBtn girBtn_3\"><span>기업정보</span></a>\r\n");
      out.write("												<a\r\n");
      out.write("													href=\"https://www.jobkorea.co.kr/Recruit/Co_Read/487603/CoRecruitLink\"\r\n");
      out.write("													target=\"_blank\" title=\"새창\" class=\"girBtn girBtn_3\"><span>진행중인\r\n");
      out.write("														채용보기</span></a>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</article>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"sumBtn\">\r\n");
      out.write("								<button type=\"button\"\r\n");
      out.write("									class=\"girBtn tplBtn_1 tplBtnOrg girBtnOrg devOnlineApplyBtn\"\r\n");
      out.write("									id=\"devApplyBtn1\">\r\n");
      out.write("									<span>즉시지원</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</section>\r\n");
      out.write("						<div id=\"detailArea\" class=\"divDetailWrap\">\r\n");
      out.write("							<!-- <div id=\"menuContainer\" class=\"devTplTabBx\">\r\n");
      out.write("								<div id=\"topMenu\" class=\"tplTabBx readTabBx\" style=\"width:1200px;\">\r\n");
      out.write("									<ul class=\"tplTab clear\">\r\n");
      out.write("										<li data-target=\"tab01\" class=\"\">\r\n");
      out.write("											<button type=\"button\">\r\n");
      out.write("												<span>상세요강</span>\r\n");
      out.write("											</button>\r\n");
      out.write("										</li>\r\n");
      out.write("										<li data-target=\"tab02\" class=\"\">\r\n");
      out.write("											<button type=\"button\">\r\n");
      out.write("												<span>접수기간/방법</span>\r\n");
      out.write("											</button>\r\n");
      out.write("										</li>\r\n");
      out.write("										<li data-target=\"tab04\" class=\"\">\r\n");
      out.write("											<button type=\"button\">\r\n");
      out.write("												<span>기업정보</span>\r\n");
      out.write("											</button>\r\n");
      out.write("										</li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div> -->\r\n");
      out.write("							<section id=\"tab01\" class=\"secReadDetail\">\r\n");
      out.write("								<h2 class=\"hd_2\">상세요강 정보</h2>\r\n");
      out.write("								<div class=\"divReadBx clear devMakeSameHeight\">\r\n");
      out.write("									<article class=\"artReadDetail\">\r\n");
      out.write("										<h3 class=\"hd_3 blind\">상세요강 정보</h3>\r\n");
      out.write("										<!-- <iframe name=\"gib_frame\" id=\"gib_frame\" width=\"1200\"\r\n");
      out.write("											scrolling=\"no\" frameborder=\"0\" marginheight=\"0\"\r\n");
      out.write("											marginwidth=\"0\" src=\"test.html\" onload=\"ifrmNavi(this)\"\r\n");
      out.write("											title=\"상세요강\"></iframe> -->\r\n");
      out.write("										<div id=\"recruitContent\" style=\"text-align: left; padding: 15px;\"></div>\r\n");
      out.write("									</article>\r\n");
      out.write("								</div>\r\n");
      out.write("							</section>\r\n");
      out.write("							<section id=\"tab02\" class=\"secReadApply\">\r\n");
      out.write("								<h2 class=\"hd_2\">접수기간/방법</h2>\r\n");
      out.write("								<div class=\"divReadBx clear devMakeSameHeight\">\r\n");
      out.write("									<article class=\"artReadPeriod\" style=\"height: 249px\">\r\n");
      out.write("										<h3 class=\"hd_3 blind\">접수기간</h3>\r\n");
      out.write("										<div>\r\n");
      out.write("											<dl class=\"time\">\r\n");
      out.write("												<dt class=\"girIcn icnTime\">남은시간</dt>\r\n");
      out.write("												<dd class=\"devRemainCount\">\r\n");
      out.write("													<span class=\"tahoma\"></span>\r\n");
      out.write("												</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("											<dl class=\"date\">\r\n");
      out.write("												<dt>시작일</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<span class=\"tahoma\"></span>\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>마감일</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<span class=\"tahoma\"></span>\r\n");
      out.write("												</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("										</div>\r\n");
      out.write("									</article>\r\n");
      out.write("									<article class=\"artReadHow\" style=\"height: 249px\">\r\n");
      out.write("										<h3 class=\"hd_3 blind\">접수방법</h3>\r\n");
      out.write("										<div class=\"tbOline\">\r\n");
      out.write("											<div class=\"btn\">\r\n");
      out.write("												<button type=\"button\"\r\n");
      out.write("													class=\"girBtn tplBtn_1 tplBtnOrg girBtnOrg devOnlineApplyBtn\"\r\n");
      out.write("													id=\"devApplyBtn2\">\r\n");
      out.write("													<span>즉시지원</span>\r\n");
      out.write("												</button>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<!-- <div class=\"tbRow tbRsm tbCase\">\r\n");
      out.write("											<dl>\r\n");
      out.write("												<dt>지원양식</dt>\r\n");
      out.write("												<dd class=\"devTplLyClick\">\r\n");
      out.write("													<strong>구지직 이력서 양식</strong>\r\n");
      out.write("												</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"tbRow\">\r\n");
      out.write("											<dl>\r\n");
      out.write("												<dt>모집분야</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<a href=\"https://www.jobkorea.co.kr/Recruit/GI_Read/44738554?rPageCode=AM&amp;logpath=21&amp;sn=6#Apply\">CDU개발팀</a>\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>모집인원</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<span class=\"tahoma\">○</span>명\r\n");
      out.write("												</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("										</div> -->\r\n");
      out.write("									</article>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"textEnd\">마감일은 기업의 사정으로 인해 조기 마감 또는 변경될 수 있습니다.</p>\r\n");
      out.write("							</section>\r\n");
      out.write("\r\n");
      out.write("							<!-- 통계 -->\r\n");
      out.write("							<!-- <section class=\"secReadStatistic\">\r\n");
      out.write("								<h2 class=\"hd_2\">지원자 현황 통계</h2>\r\n");
      out.write("\r\n");
      out.write("								<article class=\"artReadStatistic divReadBx clear blur\">\r\n");
      out.write("									<h3 class=\"hd_3 blind\">지원자 현황 통계 정보</h3>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"metricsContainer\">\r\n");
      out.write("										<div class=\"metrics metricsCount\">\r\n");
      out.write("											<div class=\"header\">지원자수</div>\r\n");
      out.write("											<div class=\"value\">\r\n");
      out.write("												<em>47</em>명\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"metrics metricsRate\">\r\n");
      out.write("											<div class=\"header\">모집인원</div>\r\n");
      out.write("											<div class=\"value\">\r\n");
      out.write("												<em>0</em>명\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"chartContainer\">\r\n");
      out.write("										<div class=\"chart chartCol_1 chartVertical\">\r\n");
      out.write("											<h4 class=\"header\">연령</h4>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">\r\n");
      out.write("														<span class=\"tahoma\">25</span>세이하\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"value\">8</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 17%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">\r\n");
      out.write("														<span class=\"tahoma\">26</span>세~<span class=\"tahoma\">30</span>세\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"value\">19</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 40%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">\r\n");
      out.write("														<span class=\"tahoma\">31</span>세~<span class=\"tahoma\">35</span>세\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"value\">10</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 21%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">\r\n");
      out.write("														<span class=\"tahoma\">36</span>세~<span class=\"tahoma\">40</span>세\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"value\">4</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 9%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">\r\n");
      out.write("														<span class=\"tahoma\">41</span>세~<span class=\"tahoma\">45</span>세\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"value\">3</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 6%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">\r\n");
      out.write("														<span class=\"tahoma\">46</span>세이상\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"value\">3</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 6%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"chart chartCol_2 chartSex\">\r\n");
      out.write("											<h4 class=\"header\">성별</h4>\r\n");
      out.write("											<div class=\"content\">\r\n");
      out.write("												<div class=\"item itemMan\">\r\n");
      out.write("													<div class=\"label\">남자</div>\r\n");
      out.write("													<div class=\"value\">36</div>\r\n");
      out.write("													<div class=\"mask\" aria-hidden=\"true\"></div>\r\n");
      out.write("													<div class=\"progress\" aria-hidden=\"true\"\r\n");
      out.write("														style=\"height: 77%\"></div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"item itemWoman\">\r\n");
      out.write("													<div class=\"label\">여자</div>\r\n");
      out.write("													<div class=\"value\">11</div>\r\n");
      out.write("													<div class=\"mask\" aria-hidden=\"true\"></div>\r\n");
      out.write("													<div class=\"progress\" aria-hidden=\"true\"\r\n");
      out.write("														style=\"height: 23%\"></div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"chart chartCol_3 chartVertical\">\r\n");
      out.write("											<h4 class=\"header\">학력</h4>\r\n");
      out.write("											<ul>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">고졸미만</div>\r\n");
      out.write("													<div class=\"value\">0</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 0%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">고졸(예정)</div>\r\n");
      out.write("													<div class=\"value\">11</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 23%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">초대졸(예정)</div>\r\n");
      out.write("													<div class=\"value\">12</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 26%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">대졸(예정)</div>\r\n");
      out.write("													<div class=\"value\">22</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 47%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("												<li>\r\n");
      out.write("													<div class=\"label\">석박사(예정)</div>\r\n");
      out.write("													<div class=\"value\">2</div>\r\n");
      out.write("													<div class=\"bar\" aria-hidden=\"true\">\r\n");
      out.write("														<div class=\"progress\" style=\"width: 4%\"></div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</article>\r\n");
      out.write("								<p class=\"btnDetail blur\">\r\n");
      out.write("									<a\r\n");
      out.write("										href=\"https://www.jobkorea.co.kr/Recruit/ApplyChart?giNo=47018175\"\r\n");
      out.write("										class=\"girBtn girBtn_4\" target=\"_blank\"><span>지원현황\r\n");
      out.write("											상세보기</span></a>\r\n");
      out.write("								</p>\r\n");
      out.write("							</section>\r\n");
      out.write("\r\n");
      out.write("							<section id=\"tab04\" class=\"secReadCoInfo\">\r\n");
      out.write("								<h2 class=\"hd_2\">기업정보</h2>\r\n");
      out.write("								<article class=\"artReadCoInfo divReadBx\">\r\n");
      out.write("									<h3 class=\"hd_3 blind\">요약정보</h3>\r\n");
      out.write("									<div class=\"tbRow clear\">\r\n");
      out.write("										<div class=\"tbCol coLogo\">\r\n");
      out.write("											<p class=\"logo\">\r\n");
      out.write("												<a\r\n");
      out.write("													href=\"https://www.jobkorea.co.kr/Recruit/Co_Read/C/487603?Oem_Code=C1\"\r\n");
      out.write("													target=\"_blank\" title=\"새창\"><img\r\n");
      out.write("													src=\"./recruit_detail_files/2j9sp006Xo_jG6ql2m28o0cpVcRt_2po.jpg\"\r\n");
      out.write("													id=\"cologo\" name=\"cologo\" alt=\"아르네코리아㈜\"\r\n");
      out.write("													onload=\"go_logo_size(this, 180, 72);\" width=\"180\"\r\n");
      out.write("													height=\"72\" /></a>\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"tbCol coInfo\">\r\n");
      out.write("											<h4 class=\"hd_4\">아르네코리아㈜</h4>\r\n");
      out.write("											<p class=\"coBtn\">\r\n");
      out.write("												<a\r\n");
      out.write("													href=\"https://www.jobkorea.co.kr/Recruit/Co_Read/C/487603?Oem_Code=C1\"\r\n");
      out.write("													target=\"_blank\" title=\"새창\" class=\"girBtn girBtn_3\"><span>기업정보</span></a>\r\n");
      out.write("											</p>\r\n");
      out.write("											<dl class=\"tbList\">\r\n");
      out.write("												<dt>산업</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<text>산업용 냉장 및 냉동 장비 제조업</text>\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>사원수</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<span class=\"tahoma\">185</span>명\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>설립</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<span class=\"tahoma\">1999</span>년 (<span class=\"tahoma\">26</span>년차)\r\n");
      out.write("												</dd>\r\n");
      out.write("												<dt>기업형태</dt>\r\n");
      out.write("												<dd>중견기업 (비상장)</dd>\r\n");
      out.write("												<dt>매출액</dt>\r\n");
      out.write("												<dd>1,380억 3,974만원</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</article>\r\n");
      out.write("\r\n");
      out.write("								<article class=\"artReadStrategy\"></article>\r\n");
      out.write("							</section> -->\r\n");
      out.write("\r\n");
      out.write("							<section class=\"secReadWork\" id=\"secReadWork\">\r\n");
      out.write("								<h2 class=\"hd_2\">근무환경</h2>\r\n");
      out.write("								<article class=\"artReadWork divReadBx\">\r\n");
      out.write("									<div class=\"location\">\r\n");
      out.write("										<div class=\"tbRow\">\r\n");
      out.write("											<dl>\r\n");
      out.write("												<dt>복리후생</dt>\r\n");
      out.write("												<dd>\r\n");
      out.write("													<dl>\r\n");
      out.write("														<dt></dt>\r\n");
      out.write("														<dd></dd>\r\n");
      out.write("													</dl>\r\n");
      out.write("													<dl>\r\n");
      out.write("														<dt>편의·여가·건강</dt>\r\n");
      out.write("														<dd>사내 동호회, 출퇴근 셔틀버스, 건강검진, 점심 식사 지원, 저녁 식사 지원, 아침 식사\r\n");
      out.write("															지원, 휴양시설, 식사 지원</dd>\r\n");
      out.write("													</dl>\r\n");
      out.write("													<dl>\r\n");
      out.write("														<dt>기타</dt>\r\n");
      out.write("														<dd>단체보험, 차량유지비수당</dd>\r\n");
      out.write("													</dl>\r\n");
      out.write("												</dd>\r\n");
      out.write("											</dl>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</article>\r\n");
      out.write("							</section>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- golgolz end -->\r\n");
      out.write("			</section>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/footer.jsp", out, false);
      out.write("  \r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
