/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-14 16:42:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.companyInfo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fcompany_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<!-- <link href=\"../assets/css/company/company-info-detail-1.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"../assets/css/company/company-info-detail-2.css\" rel=\"stylesheet\" type=\"text/css\" /> 헤더 변경됨 -->\r\n");
      out.write("    <!-- <link href=\"../assets/css/company/company-info-detail-4.css\" rel=\"stylesheet\" type=\"text/css\" /> -->\r\n");
      out.write("    <!-- <link href=\"../assets/css/company/company-info-detail-5.css\" rel=\"stylesheet\" type=\"text/css\" /> -->\r\n");
      out.write("    <!-- <link href=\"../assets/css/company/company-info-detail-6.css\" rel=\"stylesheet\" type=\"text/css\" /> -->\r\n");
      out.write("	<!-- <link href=\"../assets/css/company/company-info-detail-8.css\" rel=\"stylesheet\" type=\"text/css\" /> -->\r\n");
      out.write("    <link href=\"../assets/css/company/company-info-detail-3.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("	<link href=\"../assets/css/company/company-info-detail-7.css\" rel=\"stylesheet\" type=\"text/css\" /> \r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/lib.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- golgolz start -->\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("	<style text=\"text/css\">\r\n");
      out.write("	#companyInfoList{width:80px; height:35px; font-size:15px; margin-right:30px; margin-top:27px}\r\n");
      out.write("	#recruitmentNotice{width:120px; height:35px; font-size:15px; margin-right:30px; margin-top:27px}\r\n");
      out.write("	#companyReview{width:80px; height:35px; font-size:15px; margin-top:27px}\r\n");
      out.write("	#company_content{\r\n");
      out.write("					width: 100%; \r\n");
      out.write("					max-width: 1300px; \r\n");
      out.write("					margin: 0 auto; \r\n");
      out.write("					box-sizing: border-box;\r\n");
      out.write("					padding: 20px;\r\n");
      out.write("	}\r\n");
      out.write("	</style>\r\n");
      out.write("	<script text=\"text/javascript\">\r\n");
      out.write("		$(function(){\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"company  \">\r\n");
      out.write("    <div id=\"__next\" data-reactroot=\"\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<main class=\"JobsFeed_Jobsfeed__DpeV9\">  \r\n");
      out.write("			<section class=\"Section_Section__P1hhc\">\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"company-wrap\">\r\n");
      out.write("        <div class=\"company-header-container\">\r\n");
      out.write("            <div class=\"company-header-branding background-type4\">\r\n");
      out.write("                <div class=\"company-header-branding-container \">\r\n");
      out.write("                    <input type=\"hidden\" id=\"mId\" value=\"\" />\r\n");
      out.write("                    <input type=\"hidden\" id=\"cId\" value=\"\" />\r\n");
      out.write("                    <input type=\"hidden\" id=\"jkcId\" value=\"nexonhr\" />\r\n");
      out.write("                    <input type=\"hidden\" id=\"devPath\" value=\"https://www.jobkorea.co.kr\">\r\n");
      out.write("                    <div class=\"logo\"><a href=\"/company/1882711\"><img src=\"//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2011/10/2w1aj007Pm_gWzi2y3i2jm0djMcSj_ldjm.gif?v=202406091636&amp;hash=r&amp;serviceCode=CL\" onerror=\"companylogoOnError('//imgs.jobkorea.co.kr/img1/_whitebg/200X80/Co_Logo/Logo/2011/10/2w1aj007Pm_gWzi2y3i2jm0djMcSj_ldjm.gif?v=202406091636&amp;hash=r&amp;serviceCode=CL' , this)\" alt=\"(주)넥슨코리아 로고\" class=\"screen-out\"></a></div>\r\n");
      out.write("                    <div class=\"company-header-branding-body\">\r\n");
      out.write("                        <div class=\"special-feature\"></div>\r\n");
      out.write("                        <div class=\"name\">\r\n");
      out.write("                            (주)넥슨코리아\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"summary\">\r\n");
      out.write("                            <div class=\"summary-item\">넥슨그룹 계열사</div>\r\n");
      out.write("                            <div class=\"summary-item\">컴퓨터&#183;하드웨어&#183;장비 </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"company-nav\" role=\"navigation\">\r\n");
      out.write("                <div class=\"company-nav-container\">\r\n");
      out.write("                    <a href=\"http://localhost/recruit-app/companyInfo/user_company_detail.jsp\" class=\"company-nav-item active\">\r\n");
      out.write("                        <div class=\"name\">기업정보</div>\r\n");
      out.write("                        <div class=\"post\">\r\n");
      out.write("                            <div class=\"header screen-out\">게시물</div>\r\n");
      out.write("                            <div class=\"value\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"http://localhost/recruit-app/review/reviewResult.jsp\" class=\"company-nav-item \">\r\n");
      out.write("                        <div class=\"name\">기업리뷰</div>\r\n");
      out.write("                        <div class=\"post\">\r\n");
      out.write("                            <div class=\"header screen-out\">게시물</div>\r\n");
      out.write("                            <div class=\"value\">53</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"http://localhost/recruit-app/recruit/detail.jsp\" class=\"company-nav-item \">\r\n");
      out.write("                        <div class=\"name\">채용공고</div>\r\n");
      out.write("                        <div class=\"post\">\r\n");
      out.write("                            <div class=\"header screen-out\">게시물</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"company_content\">\r\n");
      out.write("        <input type=\"hidden\" id=\"hdnCIdent\" value=\"0fea3f631eabe498f4fed6f0e4e46f0a\" />\r\n");
      out.write("        <div class=\"company-body-infomation\">\r\n");
      out.write("            <!--기본정보 영역-->\r\n");
      out.write("            <div class=\"company-infomation-container working-environment-container working-environment-introduce fixed-height\" style=\"margin-bottom:45px; height:200px\">\r\n");
      out.write("                <h3 class=\"header\">기업소개</h3>\r\n");
      out.write("                <div class=\"introduce-body\">\r\n");
      out.write("                    <div align=\"justify\">\r\n");
      out.write("                        1994년 설립, 올해로 창립 30주년을 맞이한 (주)넥슨은 연 매출 3조 9천억원,(2023년 말 넥슨 일본법인 연결매출 기준) 사원수 3,500명 규모의 글로벌 게임회사 입니다.<br>2002년 일본, 2005년 미국, 2007년 유럽에 현지법인을 설립하며 일찌감치 해외 시장 개척에 앞장서온 넥슨은 현재 일본,중국,대만 등 동아시아 3국을 비롯해 북미지역과 유럽, 남미 등 전 세계 190여개국에 진출해 45종의 콘텐츠 서비스 중이며, 현재 19억 명의 사용자(계정)을 확보하고 있습니다. 경기도 성남시 분당구 판교로에 위치하고 있으며, 온라인, 모바일, 소셜 게임의 개발 및 서비스 사업을 하고 있습니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"company-infomation-row basic-infomation\">\r\n");
      out.write("                <h2 class=\"header\"></h2>\r\n");
      out.write("                <div class=\"company-infomation-container basic-infomation-container\">\r\n");
      out.write("                    <table class=\"table-basic-infomation-primary\" summary=\"해당 기업의 산업, 사원수, 기업구분, 설립일, 자본금, 매출액, 대표자, 주요사업, 4대보험, 주소, 홈페이지 등의 정보\">\r\n");
      out.write("                        <caption class=\"table-caption\">기업 상세 정보</caption>\r\n");
      out.write("                        <colgroup>\r\n");
      out.write("                            <col class=\"col-label\">\r\n");
      out.write("                            <col class=\"col-value\">\r\n");
      out.write("                            <col class=\"col-label\">\r\n");
      out.write("                            <col class=\"col-value\">\r\n");
      out.write("                        </colgroup>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr class=\"field\">\r\n");
      out.write("                                <th class=\"field-label\">산업</th>\r\n");
      out.write("                                <td class=\"field-value\">\r\n");
      out.write("                                    <div class=\"value-container\">\r\n");
      out.write("                                        <div class=\"value\">컴퓨터&#183;하드웨어&#183;장비</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <th class=\"field-label\">사원수</th>\r\n");
      out.write("                                <td class=\"field-value\">\r\n");
      out.write("                                    <div class=\"value-container\">\r\n");
      out.write("                                        <div class=\"values\">\r\n");
      out.write("                                            <div class=\"value\">3,500명</div>\r\n");
      out.write("                                            <div class=\"reference\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr class=\"field\">\r\n");
      out.write("                                <th class=\"field-label\">기업구분</th>\r\n");
      out.write("                                <td class=\"field-value\">\r\n");
      out.write("                                    <div class=\"value-container\">\r\n");
      out.write("                                        <div class=\"value\">대기업</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <th class=\"field-label\">설립일</th>\r\n");
      out.write("                                <td class=\"field-value\">\r\n");
      out.write("                                    <div class=\"value-container\">\r\n");
      out.write("                                        <div class=\"values\">\r\n");
      out.write("                                            <div class=\"value\">1994</div>\r\n");
      out.write("                                            <div class=\"reference\">(31년차)</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr class=\"field\">\r\n");
      out.write("                                <th class=\"field-label\">매출액</th>\r\n");
      out.write("                                <td class=\"field-value\">\r\n");
      out.write("                                    <div class=\"value-container\">\r\n");
      out.write("                                        <div class=\"values\">\r\n");
      out.write("                                            <div class=\"value\">3조 9000억</div>\r\n");
      out.write("                                            <div class=\"reference\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr class=\"field\">\r\n");
      out.write("                                <th class=\"field-label\">대표자</th>\r\n");
      out.write("                                <td class=\"field-value\">\r\n");
      out.write("                                    <div class=\"value-container\">\r\n");
      out.write("                                        <div class=\"value\">강대현&#183;김정욱</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            <tr class=\"field\">\r\n");
      out.write("                                <th class=\"field-label\">주소 </th>\r\n");
      out.write("                                <td class=\"field-value\">\r\n");
      out.write("                                    <div class=\"value-container\">\r\n");
      out.write("                                        <div class=\"value\">경기 성남시 분당구 판교로256번길 7 (삼평동) 넥슨코리아</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"company-infomation-container corporate-issues-container corporate-history fixed-height\" style=\"padding-bottom:450px\">\r\n");
      out.write("                <h3 class=\"header\">연혁</h3>\r\n");
      out.write("                <div class=\"corporate-history-list-company\">\r\n");
      out.write("                    <div class=\"corporate-history-list-item\">\r\n");
      out.write("                        <div id=\"devJKhistory\">1994년 ㈜넥슨 설립<br>1995년 세계 최장수 그래픽 온라인 게임 바람의나라 발표<br>1996년 바람의나라 정식 서비스 실시(천리안)<br>1997년 어둠의전설 발표 및 정식 서비스 실시<br>1998년 바람의나라 영문판 美상용화 / 일랜시아 발표<br>1999년 세계 최초 3D 인터넷 전략시뮬레이션 택티컬 커맨더스 발표/ 인터넷 퀴즈게임 퀴즈퀴즈(現큐플레이) 발표<br>2001년 퀴즈퀴즈 정식 서비스 실시 (전세계 최초 부분유료화 모델 - Free to Play 도입)<br> 크레이지아케이드 비엔비 발표, 정식 서비스 실시<br>2002년 넥슨 일본법인 설립, 넥슨네트웍스 설립, 아스가르드 정식 서비스 실시<br>2003년 메이플스토리 정식 서비스 실시, 최고 동시접속자수 15만명 돌파<br>2004년 종합 게임포털 넥슨(www.nexon.com) 오픈<br> 카트라이더 정식 서비스 실시, 국산게임 최초로 PC방 점유율 1위 기록<br> 마비노기 정식 서비스 실시, 대한민국 게임대상 3개 부문 수상<br> 넥슨작은책방 첫 개관(통영시 풍화분교)<br>2005년 카트라이더 최고 동시접속자수 22만명 돌파, e-스포츠 공인 공식 리그 시작<br> 메이플스토리 최고 동시접속자수 20만명 돌파<br> 넥슨아메리카 설립</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--복리후생-->\r\n");
      out.write("            <div class=\"company-infomation-container working-environment-container working-environment-benefit\" style=\"margin:auto; width:1040px; margin-top:50px\">\r\n");
      out.write("                <h3 class=\"header\">복리후생</h3>\r\n");
      out.write("                <div class=\"benefit-list\">\r\n");
      out.write("                    <div class='benefit-item-group'>\r\n");
      out.write("                        <div class=\"benefit-body\">\r\n");
      out.write("                            <p>국민연금 </p>\r\n");
      out.write("                            <p>고용보험</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"benefit-body\">\r\n");
      out.write("                            <p>경조금 </p>\r\n");
      out.write("                            <p>연차제도</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- <div class='benefit-item-group'>\r\n");
      out.write("                <div class=\"item pension\">\r\n");
      out.write("                    <div class=\"benefit-header\"> 연금&#183;보험</div>\r\n");
      out.write("                    <div class=\"benefit-body\">\r\n");
      out.write("                        <p>국민연금 </p>\r\n");
      out.write("                        <p>고용보험</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item refresh\">\r\n");
      out.write("                    <div class=\"benefit-header\"> 휴무&#183;휴가&#183;행사</div>\r\n");
      out.write("                    <div class=\"benefit-body\">\r\n");
      out.write("                        <p>주5일제</p>\r\n");
      out.write("                        <p>연차제도</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item compensation-support\">\r\n");
      out.write("                    <div class=\"benefit-header\"> 보상&#183;수당&#183;지원</div>\r\n");
      out.write("                    <div class=\"benefit-body\">\r\n");
      out.write("                        <p>퇴직금</p>\r\n");
      out.write("                        <p>경조금</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class='benefit-item-group'>\r\n");
      out.write("                <div class=\"item education \">\r\n");
      out.write("                    <div class=\"benefit-header\"> 사내제도&#183;성장</div>\r\n");
      out.write("                    <div class=\"benefit-body\">\r\n");
      out.write("                        <p>사내 외국어강좌 운영</p>\r\n");
      out.write("                        <p>신입 사원 교육</p>\r\n");
      out.write("                        <p>자율복장</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item facility-support\">\r\n");
      out.write("                    <div class=\"benefit-header\"> 사내시설</div>\r\n");
      out.write("                    <div class=\"benefit-body\">\r\n");
      out.write("                        <p>구내식당</p>\r\n");
      out.write("                        <p>휴식공간</p>\r\n");
      out.write("                        <p>탕비실</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item life\">\r\n");
      out.write("                    <div class=\"benefit-header\"> 편의&#183;여가&#183;건강</div>\r\n");
      out.write("                    <div class=\"benefit-body\">\r\n");
      out.write("                        <p>사내 동호회</p>\r\n");
      out.write("                        <p>출퇴근 셔틀버스</p>\r\n");
      out.write("                        <p>심리상담</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"company-infomation-container working-environment-container working-environment-map\" style=\"margin:auto; width:1040px; position:relative; bottom:45px;\">\r\n");
      out.write("            <h3 class=\"header\">기업위치</h3>\r\n");
      out.write("            <div class=\"address\">경기 성남시 분당구 판교로256번길 7 (삼평동) 넥슨코리아</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("   <!--  <script src=\"//i.jobkorea.kr/content/javascript/pc/dist/corp/info/ui.company.header.min-sv-202009021425.js\"\r\n");
      out.write("    type=\"text/javascript\"></script> 보류! --> \r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("			</section>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../assets/layout/user/footer.jsp", out, false);
      out.write("\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
