/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-13 14:52:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.manage.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.sist.admin.domain.user.UserQnaDomain;
import kr.co.sist.admin.domain.user.UserApplyDomain;
import java.util.List;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/recruit-app/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1716272562048L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("kr.co.sist.admin.domain.user.UserApplyDomain");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("kr.co.sist.admin.domain.user.UserQnaDomain");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.3/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$(\"#user_menu\").addClass(\"bg-gradient-primary\");\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- golgolz start -->\r\n");
      out.write("<link href=\"http://localhost//recruit-app/assets/css/pagenation.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"http://localhost//recruit-app/assets/css/manage/order/admin.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"http://localhost//recruit-app/assets/css/manage/order/reset.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"http://localhost/recruit-app/assets/css/manage/goods/general.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"http://localhost/recruit-app/assets/css/manage/goods/goods.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"http://localhost/recruit-app/assets/css/manage/goods/default.css\" rel=\"stylesheet\" />\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/layout/admin/lib.jsp", out, false);
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".subtitle{\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#dataForm div:first-child{\r\n");
      out.write("	margin-top: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container-fluid py-4 {\r\n");
      out.write("	padding-top: 0px;!important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".detail-control {\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	margin-right: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#benefits li{\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	list-style-type: decimal;\r\n");
      out.write("	list-style-position: inside;\r\n");
      out.write("	display: flex;\r\n");
      out.write("    align-items: center; /* 세로 중앙 정렬 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#benefits li:hover{\r\n");
      out.write("	background-color: #DDD;\r\n");
      out.write("}\r\n");
      out.write(".masked-data .original-data { display: none; }\r\n");
      out.write(".masked-data:hover .original-data, .masked-data .reveal-button:active + .original-data { display: inline; }\r\n");
      out.write(".masked-data:hover .masked-data-display, .masked-data .reveal-button:active + .masked-data-display { display: none; }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function(){\r\n");
      out.write("		\r\n");
      out.write("		function applyMasking(elementId, dataType) {\r\n");
      out.write("		    const $dataElement = $('#' + elementId);\r\n");
      out.write("		    const originalData = $dataElement.text();\r\n");
      out.write("		    const maskedData = maskData(originalData, dataType);\r\n");
      out.write("\r\n");
      out.write("		    $dataElement.empty().append(\r\n");
      out.write("		      $('<span>')\r\n");
      out.write("		        .addClass('masked-data')\r\n");
      out.write("		        .attr('data-original', originalData)\r\n");
      out.write("		        .attr('data-type', dataType)\r\n");
      out.write("		        .text(maskedData)\r\n");
      out.write("		    ).append(\r\n");
      out.write("		      $('<button>')\r\n");
      out.write("		        .addClass('masking-button')\r\n");
      out.write("		        .text('👁️‍🗨️')\r\n");
      out.write("		        .attr('type', 'button') \r\n");
      out.write("		        .click(function() {\r\n");
      out.write("		          toggleMasking(this);\r\n");
      out.write("		        })\r\n");
      out.write("		    );\r\n");
      out.write("		  }\r\n");
      out.write("\r\n");
      out.write("		  function toggleMasking(button) {\r\n");
      out.write("		    var $maskedData = $(button).siblings('.masked-data');\r\n");
      out.write("		    var originalData = $maskedData.attr('data-original');\r\n");
      out.write("		    var dataType = $maskedData.attr('data-type');\r\n");
      out.write("		    var currentData = $maskedData.text();\r\n");
      out.write("\r\n");
      out.write("		    if (currentData === maskData(originalData, dataType)) {\r\n");
      out.write("		      $maskedData.text(originalData);\r\n");
      out.write("		    } else {\r\n");
      out.write("		      $maskedData.text(maskData(originalData, dataType));\r\n");
      out.write("		    }\r\n");
      out.write("		  }\r\n");
      out.write("\r\n");
      out.write("		  applyMasking('nameData', 'name');\r\n");
      out.write("		  applyMasking('userIdData', 'email'); \r\n");
      out.write("		  applyMasking('phoneData', 'phone');\r\n");
      out.write("		  applyMasking('telData', 'tel'); \r\n");
      out.write("		\r\n");
      out.write("		function maskString(str, startLen = 2, endLen = 2) {\r\n");
      out.write("            if (!str) return '';\r\n");
      out.write("            const length = str.length;\r\n");
      out.write("            const maskLen = Math.max(0, length - startLen - endLen); \r\n");
      out.write("            return str.substring(0, startLen) + '*'.repeat(maskLen) + str.substring(length - endLen);\r\n");
      out.write("          }//function\r\n");
      out.write("          \r\n");
      out.write("          function maskData(data, type) {\r\n");
      out.write("          	  if (!data) return '';\r\n");
      out.write("\r\n");
      out.write("          	  switch (type) {\r\n");
      out.write("          	    case 'email':\r\n");
      out.write("          	      return maskString(data, 2, 2);\r\n");
      out.write("          	    case 'name':\r\n");
      out.write("          	      return maskString(data, 1, 1);\r\n");
      out.write("          	    case 'phone':\r\n");
      out.write("          	      const matchPhone = data.match(/^(\\d{3})-(\\d{4})-(\\d{4})$/);\r\n");
      out.write("          	      if (matchPhone) {\r\n");
      out.write("          	        return maskString(data, 4, 5); \r\n");
      out.write("          	      } else {\r\n");
      out.write("          	        return maskString(data, 4, 5); \r\n");
      out.write("          	      }\r\n");
      out.write("          	    case 'tel':\r\n");
      out.write("          	      const matchTel = data.match(/^(\\d{2})-(\\d{3})-(\\d{4})$/);\r\n");
      out.write("          	      if (matchTel) {\r\n");
      out.write("          	        return maskString(data, 3, 5); \r\n");
      out.write("          	      } else {\r\n");
      out.write("          	        return maskString(data, 4, 5); \r\n");
      out.write("          	      }\r\n");
      out.write("          	    default:\r\n");
      out.write("          	      return data; \r\n");
      out.write("          	  }\r\n");
      out.write("          	}//function\r\n");
      out.write("		\r\n");
      out.write("	});//ready\r\n");
      out.write("</script>\r\n");
      out.write("<!-- golgolz end -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/layout/admin/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<main\r\n");
      out.write("		class=\"main-content position-relative max-height-vh-100 h-100 border-radius-lg ps--active-y\">\r\n");
      out.write("		<nav\r\n");
      out.write("			class=\"navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl\"\r\n");
      out.write("			id=\"navbarBlur\" data-scroll=\"true\">\r\n");
      out.write("			<div class=\"container-fluid py-1 px-3\">\r\n");
      out.write("				<nav aria-label=\"breadcrumb\">\r\n");
      out.write("					<ol\r\n");
      out.write("						class=\"breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5\">\r\n");
      out.write("						<li class=\"breadcrumb-item text-sm\"><a\r\n");
      out.write("							class=\"opacity-5 text-dark\" href=\"javascript:;\">\r\n");
      out.write("							관리자 기능</a></li>\r\n");
      out.write("						<!-- 하단의 대시보드 텍스트를 본인 기능으로 변경 필요  -->\r\n");
      out.write("						<li class=\"breadcrumb-item text-sm text-dark active\"\r\n");
      out.write("							aria-current=\"page\">사용자 관리</li>\r\n");
      out.write("					</ol>\r\n");
      out.write("					<h6 class=\"font-weight-bolder mb-0\">회원정보 상세</h6>\r\n");
      out.write("				</nav>\r\n");
      out.write("				<p style=\"font-size: 15px; text-align: right;\">\r\n");
      out.write("							<strong>최근 로그인 일시: \r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</strong>\r\n");
      out.write("							</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div class=\"container-fluid py-4\">\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("			<div id=\"contentcolumn\" class=\"\">\r\n");
      out.write("				<div class=\"contents\">\r\n");
      out.write("					<form id=\"dataForm\" name=\"dataForm\" action=\"http://localhost/online-shop/manage/goods/register_process.jsp\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("						<div class=\"subtitle\">\r\n");
      out.write("							<img src=\"http://localhost/recruit-app/assets/images/manage/common/bul_subtitle.gif\" />\r\n");
      out.write("							기본정보\r\n");
      out.write("						</div>\r\n");
      out.write("						<table class=\"tbstyleB\" width=\"100%\">\r\n");
      out.write("						  <colgroup>\r\n");
      out.write("							    <col width=\"15%\" />\r\n");
      out.write("						    <col width=\"85%\" />\r\n");
      out.write("						  </colgroup>\r\n");
      out.write("						  <tbody>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <td class=\"label\">회원명</td>\r\n");
      out.write("						      <td class=\"box text\" id=\"nameData\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailInfo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <td class=\"label\">성별</td>\r\n");
      out.write("						      <td class=\"box text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailInfo.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <td class=\"label\">아이디</td>\r\n");
      out.write("						      <td class=\"box text\" id=\"userIdData\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailInfo.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <td class=\"label\">휴대폰번호</td>\r\n");
      out.write("						      <td class=\"box text\" id=\"phoneData\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailInfo.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("						    <tr>\r\n");
      out.write("						      <td class=\"label\">전화번호</td>\r\n");
      out.write("						      <td class=\"box text\" id=\"telData\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detailInfo.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						    </tr>\r\n");
      out.write("							  </tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<div class=\"subtitle\">\r\n");
      out.write("							<img src=\"http://localhost/recruit-app/assets/images/manage/common/bul_subtitle.gif\" />\r\n");
      out.write("							기타 인적사항\r\n");
      out.write("						</div>\r\n");
      out.write("						<table class=\"tbstyleB\" width=\"100%\">\r\n");
      out.write("							<colgroup>\r\n");
      out.write("								<col width=\"15%\" />\r\n");
      out.write("								<col width=\"85%\" />\r\n");
      out.write("							</colgroup>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"label\">가입일자</td>\r\n");
      out.write("									<td class=\"box text\">\r\n");
      out.write("									");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ detailInfo.signupDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td class=\"label\">생년월일</td>\r\n");
      out.write("									<td class=\"box text\">\r\n");
      out.write("									");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ detailInfo.birthDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<!--최근 활동 기록-->\r\n");
      out.write("						<div style=\"margin:30px 0px 30px 0px;\">\r\n");
      out.write("							<label style=\"font-size: 20px; font-weight: bold; margin: 5px 0px 5px 0px;\">최근 활동 기록</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					");

						List<UserApplyDomain> applyList = (List)request.getAttribute("applyList");
					
      out.write("\r\n");
      out.write("					<label style=\"font-size: 15px; font-weight: bold; margin: 5px 0px 5px 0px;\">최근 지원현황</label>\r\n");
      out.write("					<div class=\"tbl_head01\" style=\"margin-bottom: 50px;\">\r\n");
      out.write("					");

						if(applyList == null || applyList.size() == 0){
					
      out.write("\r\n");
      out.write("					<div style=\"text-align: center;\">\r\n");
      out.write("						<h5>현황 정보가 존재하지 않습니다.</h5>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

						}else {
					
      out.write("\r\n");
      out.write("					<table id=\"sodr_list\">\r\n");
      out.write("						<colgroup>\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("						</colgroup>\r\n");
      out.write("						<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"col\">번호</th>\r\n");
      out.write("							<th scope=\"col\">기업명</th>\r\n");
      out.write("							<th scope=\"col\">지원일자</th>\r\n");
      out.write("							<th scope=\"col\">제목</th>\r\n");
      out.write("							<th scope=\"col\">이력서상세</th>\r\n");
      out.write("							<th scope=\"col\">지원상태</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							");

							for(int i=0; i<applyList.size(); i++){
							    UserApplyDomain applyInfo = applyList.get(i);
							
      out.write("\r\n");
      out.write("							<tr class=\"list0\">\r\n");
      out.write("								<td>");
      out.print( i+1 );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( applyInfo.getCompanyName() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( applyInfo.getApplyDate() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( applyInfo.getTitle() );
      out.write(".</td>\r\n");
      out.write("								<td><input type=\"button\" value=\"바로가기\" class=\"btn btn-outline-secondary btn-sm\" style=\"font-weight: bold;margin:0px auto;\" onclick=\"location.href='http://localhost/recruit-app/manage/resumes/detail.do?id=");
      out.print( applyInfo.getResumeNum() );
      out.write("'\" /></td>\r\n");
      out.write("								<td>");
      out.print( applyInfo.getProgressState() );
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

							}//end for
						}//end else
							
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("					<label style=\"font-size: 15px; font-weight: bold; margin: 5px 0px 5px 0px;\">최근 문의사항</label>\r\n");
      out.write("					<div class=\"tbl_head01\" style=\"margin-bottom: 50px;\">\r\n");
      out.write("					");

						List<UserQnaDomain> qnaList = (List)request.getAttribute("qnaList");
					
      out.write("\r\n");
      out.write("					");

						if(qnaList == null || qnaList.size() == 0){
					
      out.write("\r\n");
      out.write("					<div style=\"text-align: center;\">\r\n");
      out.write("						<h5>문의 내역이 존재하지 않습니다.</h5>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

						}else {
					
      out.write("\r\n");
      out.write("					<table id=\"sodr_list\">\r\n");
      out.write("						<colgroup>\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("							<col class=\"w90\">\r\n");
      out.write("						</colgroup>\r\n");
      out.write("						<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th scope=\"col\">번호</th>\r\n");
      out.write("							<th scope=\"col\">카테고리</th>\r\n");
      out.write("							<th scope=\"col\">제목</th>\r\n");
      out.write("							<th scope=\"col\">문의일자</th>\r\n");
      out.write("							<th scope=\"col\">답변여부</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							");

							for(int i=0; i<qnaList.size(); i++){
							    UserQnaDomain qnaInfo = qnaList.get(i);
							
      out.write("\r\n");
      out.write("							<tr class=\"list0\">\r\n");
      out.write("								<td>");
      out.print( i+1 );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( qnaInfo.getCategory() );
      out.write("</td>\r\n");
      out.write("								<td><a href=\"http://localhost/recruit-app/manage/qna/old_detail.do?qna_num=");
      out.print( qnaInfo.getQnaNum() );
      out.write('"');
      out.write('>');
      out.print( qnaInfo.getTitle() );
      out.write("</a></td>\r\n");
      out.write("								<td>");
      out.print( qnaInfo.getInputDate() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( qnaInfo.getFlag() );
      out.write("</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							");
}//end for
      out.write("\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					");
}//end else 
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("						<div class=\"alignCenter\">\r\n");
      out.write("								<!-- <input type=\"button\" id=\"btn-register\" class=\"btn btn-outline-warning btn-sm\" value=\"저장\" /> -->\r\n");
      out.write("								<input type=\"button\" id=\"btn-back\" class=\"btn btn-outline-dark btn-sm detail-control\" value=\"닫기\" onClick=\"javascript:history.back();\"/>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	<!-- golgolz start -->\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/manage/user/detail.jsp(164,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ detailInfo.recentloginDate == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									오래 전\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/manage/user/detail.jsp(167,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ detailInfo.recentloginDate != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ detailInfo.recentloginDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
