/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-07-14 15:45:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypageUserInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  public java.lang.String getServletInfo() {
    return "";
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/layout/user/lib.jsp", out, false);
      out.write("  \r\n");
      out.write("	<!-- golgolz start -->\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 파비콘 -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"https://static.wanted.co.kr/favicon/new/favicon.ico\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://asset.wanted.co.kr/userweb/www/_next/static/css/c76e012c05e1318d.css\" crossorigin=\"anonymous\" data-n-g=\"\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"http://localhost/recruit-app/assets/css/mypage.css\"/>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"http://localhost/recruit-app/assets/css/signup.css\"/>\r\n");
      out.write("	\r\n");
      out.write("	<!-- golgolz end -->\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		<!-- golgolz start -->\r\n");
      out.write("		#profileImageContainer {\r\n");
      out.write("		    background-image: url('http://localhost/recruit-app/assets/images/mypage/uploadImg/loading.gif'); /* 로딩 이미지 배경으로 설정 */\r\n");
      out.write("		    background-size: cover;\r\n");
      out.write("		    background-position: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		<!-- golgolz end -->\r\n");
      out.write("	</style>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(function(){\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("			$(\"#modifyUser\").click(function(){\r\n");
      out.write("      		  location.href = \"http://localhost/recruit-app/user/mypage/checkPass.do\";\r\n");
      out.write("      	  	});//click\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("\r\n");
      out.write("		    var updatedProfileImg = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.profileImg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		    if (updatedProfileImg) {\r\n");
      out.write("		    	var profileImage = document.getElementById(\"profileImage\");\r\n");
      out.write("		        var profileImageContainer = document.getElementById(\"profileImageContainer\");\r\n");
      out.write("		        \r\n");
      out.write("		        function handleImageLoad() {\r\n");
      out.write("		            profileImageContainer.style.backgroundImage = \"none\";\r\n");
      out.write("		          }\r\n");
      out.write("\r\n");
      out.write("		        var xhr = new XMLHttpRequest();\r\n");
      out.write("			    xhr.open('HEAD', \"http://localhost/recruit-app/assets/images/mypage/uploadImg/\" + updatedProfileImg, true);\r\n");
      out.write("			    xhr.onload = function() {\r\n");
      out.write("			      if (xhr.status === 200) { // 이미지 파일이 존재하는 경우\r\n");
      out.write("			    	  profileImage.onload = handleImageLoad;\r\n");
      out.write("				      profileImage.src = \"http://localhost/recruit-app/assets/images/mypage/uploadImg/\" + updatedProfileImg + \"?timestamp=\" + Date.now();\r\n");
      out.write("			      }\r\n");
      out.write("			    };\r\n");
      out.write("			    xhr.send();\r\n");
      out.write("		    }\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"__next\" data-reactroot=\"\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/layout/user/header.jsp", out, false);
      out.write("\r\n");
      out.write("		<main class=\"JobsFeed_Jobsfeed__DpeV9\">  \r\n");
      out.write("			<section class=\"Section_Section__P1hhc\">\r\n");
      out.write("			<!-- golgolz start -->\r\n");
      out.write("        <div class=\"MainLayout_MainLayout__root__p6itg\">\r\n");
      out.write("          <div class=\"Grid_Grid__container__J9CcC Grid_Grid__spacing__5__ZwgDV\">\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mypage_layout.jsp", out, false);
      out.write("\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE Grid_Grid__grid__md__1__aOHPk MainLayout_MainLayout__space__8eQvZ\"\r\n");
      out.write("            ></div>\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"Grid_Grid__item__FUkSS Grid_Grid__justify_center__QJu2X Grid_Grid__align-items_flex-start__PA0JE Grid_Grid__grid__xs__12__rVqKh Grid_Grid__grid__md__6__9g_JE\"\r\n");
      out.write("            >\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"Grid_Grid__container__J9CcC Grid_Grid__direction_column__jR3AZ Grid_Grid__wrap_nowrap__4r_cp ProfileView_ProfileView__root__eOS_q\"\r\n");
      out.write("              >\r\n");
      out.write("                <section\r\n");
      out.write("                  class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE\"\r\n");
      out.write("                >\r\n");
      out.write("                  <div\r\n");
      out.write("                    class=\"Grid_Grid__container__J9CcC Grid_Grid__align-items_flex-start__PA0JE ProfileViewHeader_ProfileViewHeader__root__PjH6q\"\r\n");
      out.write("                  >\r\n");
      out.write("                    <div\r\n");
      out.write("                      class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE Grid_Grid__align-self_stretch__awciG\"\r\n");
      out.write("                    >\r\n");
      out.write("                      <div\r\n");
      out.write("                        class=\"Grid_Grid__container__J9CcC Grid_Grid__align-items_center__VEikH ProfileViewHeaderAvatar_ProfileViewHeaderAvatar__root__OR4Te\"\r\n");
      out.write("                      >\r\n");
      out.write("                        <div\r\n");
      out.write("                          class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE\"\r\n");
      out.write("                        >\r\n");
      out.write("                          <div\r\n");
      out.write("                            class=\"Avatar_Avatar__root__5Xq6z Avatar_Avatar__sizeXlarge__cwS_g ProfileViewHeaderAvatar_ProfileViewHeaderAvatar__avatar__d0_38\"\r\n");
      out.write("                          >\r\n");
      out.write("                            <div id=\"profileImageContainer\" class=\"Avatar_Avatar__bg__MRkK0\">\r\n");
      out.write("                              <img\r\n");
      out.write("                              	id=\"profileImage\"\r\n");
      out.write("                                alt=\"프로필 이미지\"\r\n");
      out.write("                                src=\"http://localhost/recruit-app/assets/images/mypage/uploadImg/loading.gif\"\r\n");
      out.write("                                class=\"Avatar_Avatar__img__kcubw\"\r\n");
      out.write("                              />\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div\r\n");
      out.write("                          class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE ProfileViewHeaderAvatar_ProfileViewHeaderAvatar__info__dUe_s\"\r\n");
      out.write("                        >\r\n");
      out.write("                          <h4\r\n");
      out.write("                            class=\"Typography_Typography__root__xYuMs Typography_Typography__heading1__bVyRs Typography_Typography__weightBold__e15ql Typography_Typography__noWrap__ovbzF Typography_Typography__alignLeft__fYbY6 ProfileViewHeaderAvatar_ProfileViewHeaderAvatar__info__title__KuxZF\"\r\n");
      out.write("                          >\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                          </h4>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <div class=\"Grid_Grid__container__J9CcC Grid_Grid__align-items_center__VEikH ProfileViewFollowerFollwingInfo_ProfileViewFollowerFollwingInfo__root__TSJnS\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <section class=\"\" >\r\n");
      out.write("                  <div\r\n");
      out.write("                    class=\"Grid_Grid__container__J9CcC Grid_Grid__item__FUkSS Grid_Grid__align-items_center__VEikH ProfileViewHeaderActions_ProfileViewHeaderActions__root__MMI7E\"\r\n");
      out.write("                  >\r\n");
      out.write("                  \r\n");
      out.write("                    <button id=\"modifyUser\" class=\"Button_Button__root__V1ie3 Button_Button__outlined__H2mkd Button_Button__outlinedAssistive__mBcQK Button_Button__outlinedSizeMedium__k3ora ProfileViewHeaderActions_ProfileViewHeaderActions__btnSetting__5erq0\">\r\n");
      out.write("                      <span class=\"Button_Button__label__1Kk0v\">정보변경</span\r\n");
      out.write("                      ><span\r\n");
      out.write("                        class=\"Button_Button__interaction__kkYaa\"\r\n");
      out.write("                      ></span></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <hr class=\"Divider_Divider__root__f2LD0 Divider_Divider__colorAlternative__nElS3\"/>\r\n");
      out.write("                <section class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE ProfileView_ProfileView__borderSection__VkDe7\" style=\"margin: 40px;\">\r\n");
      out.write("                  <h1 style=\"font-size: 25px; text-align: center\"><strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님, 환영해요.</strong></h1>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section\r\n");
      out.write("                  class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE\"\r\n");
      out.write("                >\r\n");
      out.write("                  <article class=\"css-dnwsdj\">\r\n");
      out.write("                  <div class=\"css-9as5im\">\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#000000\" class=\"css-dk1ca0\">사용자 정보</p>\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"rgba(55, 56, 60, 0.61)\" class=\"css-1b12nwt\">서비스에서 사용하는 내 사용자 정보를 관리할 수 있습니다.</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <ul class=\"css-14jv0iu\">\r\n");
      out.write("                  <li data-list-type=\"EMAIL_CHANGE\" tabindex=\"0\" class=\"css-1f5onls\">\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#000000\" class=\"css-9dug5j\">이메일</p>\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#171719\" class=\"css-j2itip\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p> </li>\r\n");
      out.write("                  <li data-list-type=\"NAME_CHANGE\" tabindex=\"0\" class=\"css-15hfbq8\">\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#000000\" class=\"css-9dug5j\">이름</p>\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#171719\" class=\"css-j2itip\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li data-list-type=\"NAME_CHANGE\" tabindex=\"0\" class=\"css-15hfbq8\">\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#000000\" class=\"css-9dug5j\">성별</p>\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#171719\" class=\"css-j2itip\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.gender }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li data-list-type=\"PHONE_CHANGE\" tabindex=\"0\" class=\"css-xr5rwo\"><p color=\"#000000\" class=\"css-9dug5j\">휴대폰 번호</p>\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#171719\" class=\"css-j2itip\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li data-list-type=\"PHONE_CHANGE\" tabindex=\"0\" class=\"css-xr5rwo\"><p color=\"#000000\" class=\"css-9dug5j\">전화번호</p>\r\n");
      out.write("                  <p data-testid=\"Typography\" color=\"#171719\" class=\"css-j2itip\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userInfo.tel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  </ul></article>\r\n");
      out.write("                </section>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"Grid_Grid__item__FUkSS Grid_Grid__align-items_flex-start__PA0JE Grid_Grid__grid__md__1__aOHPk MainLayout_MainLayout__space__8eQvZ\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("			<!-- golgolz end -->\r\n");
      out.write("			</section>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../assets/layout/user/footer.jsp", out, false);
      out.write("\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
